package com.vartala.soulofw0lf.rpgclasses;

import java.util.ArrayList;

import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

public class statChooser {

	public static void baseStats(Player p, String string) {
			Inventory inv = Bukkit.createInventory(null, 9, p.getName() + " Stats:");
			//tank item
			ItemStack str = new ItemStack(267, 10);
			ItemMeta strim = str.getItemMeta();
			strim.setDisplayName("§4Strength");
			ArrayList<String> strlore = new ArrayList<String>();
			strlore.add("§FThis represents your physical strength");
			strlore.add("§Fand for most classes determines how well");
			strlore.add("§Fand how hard you hit.");
			strlore.add("Current Class:");
			strlore.add(string);
			strim.setLore(strlore);
			str.setItemMeta(strim);
			inv.setItem(0, str);
			//caster item
			ItemStack dex = new ItemStack(317, 10);
			ItemMeta dexim = dex.getItemMeta();
			dexim.setDisplayName("§4Dexterity");
			ArrayList<String> dexlore = new ArrayList<String>();
			dexlore.add("§FThis represents your fluidity of movement");
			dexlore.add("§Fand for most classes determines how hard");
			dexlore.add("§Fyou are to hit. Classes that have this");
			dexlore.add("§Fas a primary stat use Dex instead of");
			dexlore.add("§Fstrength for hit and damage.");
			dexlore.add("Current Class:");
			dexlore.add(string);
			dexim.setLore(dexlore);
			dex.setItemMeta(dexim);
			inv.setItem(1, dex);
			ItemStack con = new ItemStack(303, 10);
			ItemMeta conim = con.getItemMeta();
			conim.setDisplayName("§4Constitution");
			ArrayList<String> conlore = new ArrayList<String>();
			conlore.add("§FThis represents your physical health");
			conlore.add("§Fand for all classes determines your");
			conlore.add("§Ftotal hit points.");
			conlore.add("Current Class:");
			conlore.add(string);
			conim.setLore(conlore);
			con.setItemMeta(conim);
			inv.setItem(2, con);
			ItemStack intel = new ItemStack(387, 10);
			ItemMeta intelim = intel.getItemMeta();
			intelim.setDisplayName("§4Intelligence");
			ArrayList<String> intellore = new ArrayList<String>();
			intellore.add("§FThis represents your mental Discipline");
			intellore.add("§FIntelligence is a primary caster stat.");
			intellore.add("Current Class:");
			intellore.add(string);
			intelim.setLore(intellore);
			intel.setItemMeta(intelim);
			inv.setItem(3, intel);
			ItemStack wis = new ItemStack(260, 10);
			ItemMeta wisim = wis.getItemMeta();
			wisim.setDisplayName("§4Wisdom");
			ArrayList<String> wislore = new ArrayList<String>();
			wislore.add("§FThis represents your mental prowess");
			wislore.add("§FWisdom is a primary caster stat.");
			wislore.add("Current Class:");
			wislore.add(string);
			wisim.setLore(wislore);
			wis.setItemMeta(wisim);
			inv.setItem(4, wis);
			ItemStack cha = new ItemStack(388, 10);
			ItemMeta chaim = cha.getItemMeta();
			chaim.setDisplayName("§4Charisma");
			ArrayList<String> chalore = new ArrayList<String>();
			chalore.add("§FThis represents your physical beauty");
			chalore.add("§Fand social skills.");
			chalore.add("Current Class:");
			chalore.add(string);
			chaim.setLore(chalore);
			cha.setItemMeta(chaim);
			inv.setItem(5, cha);
			ItemStack melee = new ItemStack(133, 25);
			ItemMeta meleeim = melee.getItemMeta();
			meleeim.setDisplayName("§4Points Remaining");
			ArrayList<String> mellore = new ArrayList<String>();
			mellore.add("§FYou must spend all your points");
			mellore.add("§Fbefore proceeding.");
			mellore.add("click here to reset your stats.");
			mellore.add("Current Class:");
			mellore.add(string);
			meleeim.setLore(mellore);
			melee.setItemMeta(meleeim);
			inv.setItem(8, melee);
			p.openInventory(inv);
	}
	public static void statConfirm(Player p, String string, Integer str1, Integer dex1, Integer con1, Integer intel1, Integer wis1, Integer cha1){
		Inventory inv = Bukkit.createInventory(null, 18, "Final Confirm:");
		//tank item
		ItemStack melee = new ItemStack(267);
		ItemMeta meleeim = melee.getItemMeta();
		meleeim.setDisplayName("§4Confirm Stats");
		ArrayList<String> mellore = new ArrayList<String>();
		mellore.add("§FThis Decision is §4Final!!");
		mellore.add("§FPlease only click here if you are sure");
		mellore.add("§Fthat these are the stats you want!");
		meleeim.setLore(mellore);
		melee.setItemMeta(meleeim);
		inv.setItem(3, melee);
		//caster item
		ItemStack ranged = new ItemStack(152);
		ItemMeta rangedim = ranged.getItemMeta();
		rangedim.setDisplayName("Previous Menu");
		ArrayList<String> ranglore = new ArrayList<String>();
		ranglore.add("§FNot happy with these stat selections?");
		ranglore.add("§FClick here to return to the previous");
		ranglore.add("§FMenu");
		rangedim.setLore(ranglore);
		ranged.setItemMeta(rangedim);
		inv.setItem(7, ranged);
		//
		ItemStack str = new ItemStack(267, str1);
		ItemMeta strim = str.getItemMeta();
		strim.setDisplayName("§4Strength");
		ArrayList<String> strlore = new ArrayList<String>();
		strlore.add("§FThis represents your physical strength");
		strlore.add("§Fand for most classes determines how well");
		strlore.add("§Fand how hard you hit.");
		strlore.add("Current Class:");
		strlore.add(string);
		strim.setLore(strlore);
		str.setItemMeta(strim);
		inv.setItem(10, str);
		//caster item
		ItemStack dex = new ItemStack(317, dex1);
		ItemMeta dexim = dex.getItemMeta();
		dexim.setDisplayName("§4Dexterity");
		ArrayList<String> dexlore = new ArrayList<String>();
		dexlore.add("§FThis represents your fluidity of movement");
		dexlore.add("§Fand for most classes determines how hard");
		dexlore.add("§Fyou are to hit. Classes that have this");
		dexlore.add("§Fas a primary stat use Dex instead of");
		dexlore.add("§Fstrength for hit and damage.");
		dexlore.add("Current Class:");
		dexlore.add(string);
		dexim.setLore(dexlore);
		dex.setItemMeta(dexim);
		inv.setItem(11, dex);
		ItemStack con = new ItemStack(303, con1);
		ItemMeta conim = con.getItemMeta();
		conim.setDisplayName("§4Constitution");
		ArrayList<String> conlore = new ArrayList<String>();
		conlore.add("§FThis represents your physical health");
		conlore.add("§Fand for all classes determines your");
		conlore.add("§Ftotal hit points.");
		conlore.add("Current Class:");
		conlore.add(string);
		conim.setLore(conlore);
		con.setItemMeta(conim);
		inv.setItem(12, con);
		ItemStack intel = new ItemStack(387, intel1);
		ItemMeta intelim = intel.getItemMeta();
		intelim.setDisplayName("§4Intelligence");
		ArrayList<String> intellore = new ArrayList<String>();
		intellore.add("§FThis represents your mental Discipline");
		intellore.add("§FIntelligence is a primary caster stat.");
		intellore.add("Current Class:");
		intellore.add(string);
		intelim.setLore(intellore);
		intel.setItemMeta(intelim);
		inv.setItem(14, intel);
		ItemStack wis = new ItemStack(260, wis1);
		ItemMeta wisim = wis.getItemMeta();
		wisim.setDisplayName("§4Wisdom");
		ArrayList<String> wislore = new ArrayList<String>();
		wislore.add("§FThis represents your mental prowess");
		wislore.add("§FWisdom is a primary caster stat.");
		wislore.add("Current Class:");
		wislore.add(string);
		wisim.setLore(wislore);
		wis.setItemMeta(wisim);
		inv.setItem(15, wis);
		ItemStack cha = new ItemStack(388, cha1);
		ItemMeta chaim = cha.getItemMeta();
		chaim.setDisplayName("§4Charisma");
		ArrayList<String> chalore = new ArrayList<String>();
		chalore.add("§FThis represents your physical beauty");
		chalore.add("§Fand social skills.");
		chalore.add("Current Class:");
		chalore.add(string);
		chaim.setLore(chalore);
		cha.setItemMeta(chaim);
		inv.setItem(16, cha);
		p.openInventory(inv);
	}
}
